# Generated by Django 4.2.6 on 2023-10-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('forma_pago', models.CharField(max_length=20)),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
                ('adultos', models.PositiveIntegerField()),
                ('ninos', models.PositiveIntegerField()),
                ('edad_ninos', models.PositiveIntegerField()),
                ('desayunos_buffete', models.PositiveIntegerField()),
                ('dias_renta_auto', models.PositiveIntegerField()),
                ('codigo_tarifa_unico', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
            ],
        ),
    ]
