# Generated by Django 4.2.6 on 2023-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('triple', 'Triple'), ('matrimonial', 'Matrimonial')], max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='habitacion_fotos/')),
            ],
        ),
    ]
